### ISSUE TITLE
Please explain what does this plugin do

### ISSUE THREAD

**Issue by Birowsky** [jlagerweij/elm-external-tools#1]

**Comment by jlagerweij** [comment]
Elm-external-tools performs `elm-make` on your Elm files and shows compile error messages inline. Idea is based on the Atom plugin https://atom.io/packages/linter-elm-make, which uses `elm-make` too show detailed error messages. I have added a description in the README.md to explain this plugin more.

Thank you for your comment.

**Comment by Birowsky** [comment]
Awesome, man, thank you! You shouldn't keep this to yourself :}
