### ISSUE TITLE
"Elm 0.0.0 is not supported" and falsely flagged case statements

### ISSUE THREAD

**Issue by tylerperkins** [jlagerweij/elm-external-tools#8]
Since upgrading my project to Elm 0.19.0, I always see this at the top of the page, along with links "Setup toolchain" and "Do not show again". Clicking the former link shows that the plugin knows the correct Elm version.

I cloned Evan's [tutorial](https://github.com/evancz/elm-architecture-tutorial) and tried it too. The plugin prompted me for a couple things (e.g., it couldn't find `elm.json`!), but then still said "Elm 0.0.0 is not supported".

Don't know if it's related, but there's a potentially more serious problem: The first `case` statement in each `.elm` file of the tutorial is flagged, "Case expression is not exhaustive".

FYI:
```
    > which elm node
    /usr/local/bin/elm
    /usr/local/bin/node
```

**Comment by klazuka** [comment]
@tylerperkins can you check these 2 screens for me and post your corresponding screenshots?

<img width="922" alt="screen shot 2019-02-06 at 11 07 35 am" src="https://user-images.githubusercontent.com/84525/52366934-bd400700-29ff-11e9-9fb7-4cdf12f976bb.png">

<img width="887" alt="screen shot 2019-02-06 at 11 08 27 am" src="https://user-images.githubusercontent.com/84525/52366937-c0d38e00-29ff-11e9-96c2-bce7f3d5164d.png">

As for that example with the "case expression is not exhaustive" errors, I suspect that this is a downstream error due to the project not being fully configured. When I loaded the example in my project, it worked fine. So let's first troubleshoot the project configuration problems, and then we can deal with the `case` error later if it still happens.

**Comment by tylerperkins** [comment]
Those screens look OK to me. What do you think?

![image](https://user-images.githubusercontent.com/607877/52382702-8ab00180-2a33-11e9-8842-df6772d17936.png)

![image](https://user-images.githubusercontent.com/607877/52382473-a961c880-2a32-11e9-9d80-33d014de7f3e.png)

**Comment by klazuka** [comment]
Thanks. It looks properly configured. I recently added a cache on the Elm version check. Is it still broken after restarting IntelliJ? 

Another thing you can try is updating to 2.2.3 (https://github.com/klazuka/intellij-elm/releases/tag/v2.2.3, or wait for it to appear in the JetBrains plugin repo later this week). 

Finally, can you past the output of running ‘/usr/local/bin/elm --version’?

**Comment by tylerperkins** [comment]
Yup, still broken even after doing ** File --> Invalidate Caches / Restart ... **

```
>  /usr/local/bin/elm --version
0.19.0
```

OK, I uninstalled Elm External Tools, restarted, and was surprised to see that the problem remained (considering the `case` problem). I then uninstalled the Elm 2.2.2 plugin and restarted, and of course the problems were gone. Then I installed Elm 2.2.3 and the problems returned.

One thing I noticed might be important: In both Elm 2.2.2 and 2.2.3, when I open the **Languages & Frameworks > Elm** preference page, I see the correct path to the `elm` executable, `/usr/local/bin`, but the "Elm version" field says, "not available". But if I just touch the path, say by typing a character and deleting it, there's a pause of a second or so, then "0.19.0" appears, as shown in my screen shot. I then click OK to dismiss the dialog, the problems remain, so I open up the Elm page once more. Again, "not available" appears.

**Comment by klazuka** [comment]
Hmm. I will look into making a new build with some more logging. In the meantime, one thing you can try is going to IntelliJ's menu bar and select **Tools > Elm > Refresh Elm projects**. But that's a long-shot.

Can you provide a little more detail about your environment. Are you running IntelliJ? WebStorm? What's the version number? How did you install Elm? Via the Elm installer or npm?

Thanks for your patience.

**Comment by tylerperkins** [comment]
Well, **Refresh Elm projects** had no effect, but I noticed the other menu item, **Attach Elm JSON project file**. So I tried it. I just clicked **OK** in the dialog, since it already showed the correct _elm.json_ file, and guess what? The "Elm 0.0.0 is not supported" banner went away! Sadly, I restarted IntelliJ and it's back. The **Elm** preference page still behaves as I described above, and the "Case expression is not exhaustive" problem is still there.

I'm running IntellJ IDEA Ultimate 2018.3.4, build #U-183.5429.30 (the latest release, as of today). I had originally installed elm with Homebrew, if memory serves, but then decided that so many tools, interop. etc. require NPM that I might as well keep them all managed by npm. So I brew-uninstalled elm and npm-installed it.
```
> npm --version
6.7.0

> node --version
v11.9.0
```
Thanks for your great work, and I hope this helps!

**Comment by jlagerweij** [comment]
I do realize this issue does not have anything to do with Elm External Tools project, but I do have seen something similar when developing the elm-external-tools plugin. I too have had Elm installed using brew but a user decided to use nvm and npm to install Elm. As IntelliJ does not have the normal nvm settings from the terminal, node could not be found when executing `elm` as the `elm` binary is no longer a binary, but a script starting `node` with elm as param. My solution was to ask for a `node` binary to run the elm script with. @tylerperkins Might I suggest for you to try to use the `elm` binary again to see if that solves some of the issues?

**Comment by klazuka** [comment]
yeah, I just had a report from an `nvm` user [about the same thing](https://github.com/klazuka/intellij-elm/issues/252). They ended up solving the problem by providing a path to the actual Elm binary, not the wrapper script that **looks like** the binary. I'm going to have to add some checks here to detect this situation. But if that were the case here, I would expect it to always fail. But @tylerperkins reports that it sometimes succeeds in invoking the Elm compiler and reading out the version.

**Comment by tylerperkins** [comment]
That's it! Yes, it makes sense that if (1) IntelliJ finds node in the same directory as the elm file specified in the preference page, (2) it runs node with that elm javascript file as argument, but without the user's environment, then (3) node can't find elm because it doesn't have the user's $PATH.

I npm-uninstalled elm, then reinstalled it with the Elm installer for MacOS. It does indeed install /usr/local/bin/elm, which is a binary. The **Elm** preference page behaves normally now, and the "Elm 0.0.0 is not supported" banner is gone. I also reinstalled Elm External Tools, which appears to be working fine.

The "Case expression is not exhaustive" issue is still present, however. @klazuka, would you like me to make a new issue for it in [intellij-elm](https://github.com/klazuka/intellij-elm)?

**Comment by klazuka** [comment]
@tylerperkins I'm glad that worked. I will improve the detection/configuration process. As for the case expression bug, if you're seeing the false positive running version 2.2.3, then, yes, go ahead and post it.

@jlagerweij thanks for jumping in 😄

**Comment by jlagerweij** [comment]
Just today a colleague of mine got the 'Case is not exhaustive' message and I just saw it myself. After updating to 2.2.3, that message was gone for at least. I hope it's also gone for @tylerperkins.

@klazuka Thank you for your excellent Elm plugin.

**Comment by tylerperkins** [comment]
As promised, I've opened a new issue about the `case` statement in the Elm plugin repo [here](https://github.com/klazuka/intellij-elm/issues/260)
